version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    restart: unless-stopped

  kafka1:
    image: confluentinc/cp-kafka:7.4.0
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_HEAP_OPTS: "-Xmx256m -Xms128m"
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    restart: unless-stopped

  kafka2:
    image: confluentinc/cp-kafka:7.4.0
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_HEAP_OPTS: "-Xmx256m -Xms128m"
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
    restart: unless-stopped

  kafka3:
    image: confluentinc/cp-kafka:7.4.0
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9094
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_HEAP_OPTS: "-Xmx256m -Xms128m"
    depends_on:
      - zookeeper
    ports:
      - "9094:9094"
    restart: unless-stopped

  db_master:
    image: postgres:15
    container_name: db_master
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: boulangerie
    volumes:
      - ./postgres/setup-master.sh:/docker-entrypoint-initdb.d/setup-master.sh:ro
      - ./postgres/init_master.sql:/docker-entrypoint-initdb.d/init_master.sql:ro
      - master-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  db_slave:
    image: postgres:15
    container_name: db_slave
    depends_on:
      - db_master
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: boulangerie
    volumes:
      - ./postgres/setup-slave.sh:/docker-entrypoint-initdb.d/setup-slave.sh:ro
      - ./postgres/init_slave.sql:/docker-entrypoint-initdb.d/init_slave.sql:ro
      - slave-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: unless-stopped

  api_write:
    build: ./api_write
    ports:
      - "8001:8000"
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka1:9092,kafka2:9093,kafka3:9094"

  api_read:
    build: ./api_read
    ports:
      - "8002:8000"
    depends_on:
      - db_slave

  sync:
    build: ./sync
    container_name: sync_service
    depends_on:
      - kafka1
      - kafka2
      - kafka3
      - db_master
    environment:
      DB_HOST: db_master
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: pass
      DB_NAME: boulangerie
      KAFKA_BOOTSTRAP_SERVERS: "kafka1:9092,kafka2:9093,kafka3:9094"
      TOPIC: pains
    restart: unless-stopped

volumes:
  master-data:
  slave-data: