apiVersion: v1
kind: Service
metadata:
  name: api-write-svc
spec:
  type: {{ .Values.apiWrite.service.type }}
  ports:
    - port: {{ .Values.apiWrite.service.port }}
      targetPort: {{ .Values.apiWrite.service.targetPort }}
      nodePort: {{ .Values.apiWrite.service.nodePort }}
  selector:
    app: {{ .Values.apiWrite.app }}